// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
public sealed partial class UserNewPropertyActive : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(UserNewPropertyActive));
    
    string IMigrationMetadata.Id
    {
        get { return "201504041006586_UserNewPropertyActive"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
