// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
public sealed partial class UserCustomMap : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(UserCustomMap));
    
    string IMigrationMetadata.Id
    {
        get { return "201503071338045_UserCustomMap"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
